language: c
sudo: false
matrix:
  include:
    - os: linux
      env: PYTHON_VERSION=3.5
    - os: linux
      env: PYTHON_VERSION=3.6
    - os: linux
      env: PYTHON_VERSION=3.7
    - os: osx
      env: PYTHON_VERSION=3.7
    - os: windows
      env: PYTHON_VERSION=3.7
before_install:
  - wget https://raw.githubusercontent.com/trichter/conda4travis/latest/conda4travis.sh -O conda4travis.sh
  - source conda4travis.sh
  - conda config --add channels conda-forge
  - conda create -q -n testenv python=$PYTHON_VERSION numpy obspy h5py coverage
  - conda activate testenv
  - conda list
install:
  - pip install -v --no-deps .
script:
  - mkdir empty; cd empty
  - coverage run ../test_obspyh5.py
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
    email: false
